import Head from 'next/head';
import { useState } from 'react';
import { BiUserPlus } from 'react-icons/bi';

import { ShowFormType } from 'src/common/types/ShowFormType';
import { Button, Table } from '~/base/.';
import { FormEmployee } from '~/ui/FormEmployee';

import styles from '../common/styles/Home.module.scss';

export default function Home() {
  const [showForm, setShowForm] = useState<ShowFormType>({
    type: 'add',
    visible: false,
  });

  const handleShowForm = () => {
    setShowForm({
      type: 'add',
      visible: !showForm.visible,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Management
        </h1>

        <div className="container mx-auto justify-between py-5 border-b">
          <div className="left flex gap-3 pb-5">
            <Button color="indigo" onClick={handleShowForm}>
              Add Employee{' '}
              <span>
                <BiUserPlus />
              </span>
            </Button>
          </div>

          {/* Clossable Form */}
          <div className="container mx-auto">
            {showForm.visible && (
              <FormEmployee showForm={showForm} setShowForm={setShowForm} />
            )}
          </div>

          {/* Table */}
        </div>
        <div className="container mx-auto">
          <Table setShowForm={setShowForm} />
        </div>
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
}
